name: Autograde

on: [push]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t student-app .

    - name: Run container
      run: |
        docker run -d --rm -p 80:80 --name student-app student-app
        sleep 5

    - name: Test server
      run: |
        curl -s http://localhost:80 > result.txt || echo "fail" > result.txt
        cat result.txt

    - name: Grade
      run: |
        if grep -q "hello cnu computer network is fun" result.txt; then
          echo "SCORE: 100"
        else
          echo "SCORE: 0"
        fi

    - name: Stop container
      run: docker stop student-app || true
